### ISSUE TITLE
Game randomly freezes

### ISSUE THREAD

**Issue by unquenchedservant** [chillhumanoid/uno#2]
Okay so it randomly freezes at random points. I have to figure out why

**Comment by unquenchedservant** [comment]
working on fixing this now, should be fixed by midweek

**Comment by trekk** [comment]
its because of your loops, the program has to go through so many loops and statements that it takes a while to process. Work on efficiency.

**Comment by unquenchedservant** [comment]
yea i just let it run while I went out and did something, came back to an out of memory issue XD

**Comment by trekk** [comment]
just clean up your nested loops, every time you have a nested loop, you increase processing time exponentially.
